apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness
spec:
  selector:
    matchLabels:
      app: liveness-http
  replicas: 1
  template:
    metadata:
      labels:
        app: liveness-http
    spec:
      containers:
        - name: liveness
          image: demo
          imagePullPolicy: IfNotPresent
          ports:
          - name: liveness-port
            containerPort: 8080
           
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080          
            initialDelaySeconds: 3
            periodSeconds: 3